 ```toml
 [build]
   command = "npm run build"
   publish = "." # Or your publish directory if different, e.g., "dist" or "build"

 [build.environment]
   NODE_VERSION = "18" # Specify the Node.js version you want Netlify to use
 ```
